services:
   postgres-autopark:
    image: postgres:alpine
    restart: always
    container_name: postgres-autopark
    networks:
      - autopark-backend
    environment:      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

   service-autopark:
    image: golang:1.21
    depends_on:
      - postgres-autopark
    container_name: service-autopark
    networks:
      - autopark-backend
    ports:
      - 15000:8081
    volumes:
      - ./:/service-autopark
    working_dir: /service-autopark
    command: "go run cmd/server/main.go"

networks:
  autopark-backend:
    driver: bridge
    name: autopark-backend