services:
  api-gateway-nginx:
    container_name: api-gateway-nginx
    image: nginx:alpine
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80