CREATE TABLE ADMINS(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(255) UNIQUE NOT NULL,
    PWD VARCHAR(255) NOT NULL
);

CREATE TABLE MANAGERS(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(255) UNIQUE NOT NULL,
    PWD VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTS(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(255) UNIQUE NOT NULL,
    PWD VARCHAR(255) NOT NULL
);

INSERT INTO ADMINS VALUES(default, 'admin', 'admin');
INSERT INTO ADMINS VALUES(default, 'admin1', 'admin1');
INSERT INTO ADMINS VALUES(default, 'admin2', 'admin2');


INSERT INTO MANAGERS VALUES(DEFAULT, 'alex', 'pirogov');
INSERT INTO MANAGERS VALUES(DEFAULT, 'ivan', 'borisov');
INSERT INTO MANAGERS VALUES(DEFAULT, 'andrei', 'ivanov');

INSERT INTO CLIENTS VALUES(default, 'client', 'client');
INSERT INTO CLIENTS VALUES(default, 'client1', 'client1');