services:
   manager-service-db:
    image: postgres:alpine
    restart: always
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 10010:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql