services:
   postgres-enterprise:
    image: postgres:alpine
    container_name: postgres-enterprise
    restart: always
    networks:
      - autopark-backend
    environment:      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

   service-enterprise:
     image: golang:1.21
     container_name: service-enterprise
     networks:
       - autopark-backend
     ports:
       - 15020:8080
     volumes:
       - ./:/service-enterprise
     working_dir: /service-enterprise
     command: "go run cmd/server/main.go"

networks:
  autopark-backend:
    driver: bridge
    name: autopark-backend