services:
   enterprise-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 10000:10000
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql