CREATE TABLE ENTERPRISES(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(500)
);

CREATE TABLE CREDS(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(500),
    PWD VARCHAR(500)
);

CREATE TABLE MANAGERS(
    ID SERIAL PRIMARY KEY,
    E_ID BIGINT,
    LOGIN VARCHAR(500),
    PWD VARCHAR(500),
    CONSTRAINT FK_ENTERPRISE_MANAGER FOREIGN KEY(E_ID) REFERENCES ENTERPRISES(ID)
);