CREATE TYPE BOOKING_STATUS AS ENUM('created', 'car_choosed', 'approved', 'finished', 'canceled');

CREATE TABLE BOOKINGS(
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    CAR_ID INT NOT NULL DEFAULT -1,
    STATUS BOOKING_STATUS NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP NOT NULL
);